# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'FindMyGoat' do
	pod 'RealmSwift'
    pod 'RealmMapView'
end

post_install do |installer|
    `rm -rf Pods/Headers`
end

