#!/bin/bash
# DO NOT EDIT THIS FILE

ocamlbuild -pkgs oUnit part2.ml
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Your code currently does not compile.  You will receive
little to no credit for submitting this code. Check the
error messages above carefully to determine what is wrong.
===========================================================
EOF
  exit 1
fi

cat >checktypes.ml <<EOF
(* DO NOT EDIT THIS FILE *)
type card = Part2.card
let check_make_card : int -> string -> card = Part2.make_card
let check_string_of_card : card -> string = Part2.string_of_card
let check_beats : card list -> card list -> bool = Part2.beats
let check_can_access : (int * int list) list -> int -> int list = Part2.can_access
EOF

if ocamlbuild -pkgs oUnit checktypes.byte ; then
  cat <<EOF
===========================================================
Your function names and types look good to me.
Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Your function names and types look broken to me.  The code
that you submit might not compile on the grader's machine,
leading to heavy penalties.  Please fix your names and
types.  Check the error messages above carefully to
determine what is wrong. 
===========================================================
EOF
fi

